/**
 * 中文（简体）翻译
 * 专业术语不翻译：Skills、Plugins、Commands、Sessions、OpenCode、OpenPackage、OpenWork、MCPs
 */

export default {
  // ==================== Dashboard ====================
  "dashboard.title": "主页",
  "dashboard.sessions": "会话",
  "dashboard.commands": "Commands",
  "dashboard.skills": "Skills",
  "dashboard.plugins": "插件",
  "dashboard.mcps": "MCPs",
  "dashboard.settings": "设置",
  "dashboard.home": "主页",
  "dashboard.runs": "运行",
  "dashboard.find_workspace": "查找工作区...",
  "dashboard.workspaces": "工作区",
  "dashboard.no_workspaces": "没有匹配的工作区。",
  "dashboard.new_workspace": "新建工作区...",
  "dashboard.new_remote_workspace": "添加远程工作区...",
  "dashboard.forget_workspace": "忘记工作区",
  "dashboard.remote": "远程",
  "dashboard.connection": "连接",
  "dashboard.local_engine": "本地引擎",
  "dashboard.client_mode": "客户端模式",
  "dashboard.connected": "已连接",
  "dashboard.not_connected": "未连接",
  "dashboard.stop_disconnect": "停止并断开",
  "dashboard.disconnect": "断开连接",
  "dashboard.new_task": "新建任务",
  "dashboard.new": "新建",
  "dashboard.busy": "忙碌",
  "dashboard.hero_title": "今天想做些什么？",
  "dashboard.hero_description": "描述一个目标。OpenWork 将运行它并保留审计记录。",
  "dashboard.quick_start_commands": "快速开始命令",
  "dashboard.view_all": "查看全部",
  "dashboard.no_commands": "还没有命令。初始命令将显示在这里。",
  "dashboard.run_command": "运行保存的命令",
  "dashboard.recent_sessions": "最近的会话",
  "dashboard.this_workspace": "此工作区",
  "dashboard.no_sessions": "还没有会话。",
  "dashboard.idle": "空闲",
  "dashboard.running": "运行中",
  "dashboard.completed": "已完成",
  "dashboard.failed": "失败",
  "dashboard.repairing_cache": "正在修复缓存",
  "dashboard.repair_cache": "修复缓存",
  "dashboard.retry": "重试",
  "dashboard.alpha": "测试版",
  "dashboard.create_workspace_title": "创建工作区",
  "dashboard.create_workspace_subtitle": "初始化新的基于文件夹的工作区。",
  "dashboard.create_workspace_confirm": "创建工作区",
  "dashboard.create_sandbox_confirm": "创建为沙盒",
  "dashboard.sandbox_get_ready_title": "沙盒需要 Docker",
  "dashboard.sandbox_get_ready_action": "准备沙盒环境",
  "dashboard.sandbox_get_ready_desc": "在隔离的 Docker 容器中运行此工作区，更安全、更可复现。",
  "dashboard.sandbox_checking_docker": "正在检查 Docker...",
  "dashboard.create_remote_workspace_title": "添加远程工作区",
  "dashboard.create_remote_workspace_subtitle": "保存 OpenWork 服务器为工作区。",
  "dashboard.create_remote_workspace_confirm": "添加工作区",
  "dashboard.edit_remote_workspace_title": "编辑远程连接",
  "dashboard.edit_remote_workspace_subtitle": "更新此工作区的 OpenWork 服务器信息。",
  "dashboard.edit_remote_workspace_confirm": "保存连接",
  "dashboard.remote_workspace_title": "远程工作区",
  "dashboard.remote_workspace_hint": "记录 OpenWork 服务器，随时重新连接。",
  "dashboard.remote_base_url_label": "OpenWork 服务器地址",
  "dashboard.remote_base_url_placeholder": "http://127.0.0.1:8787",
  "dashboard.remote_base_url_required": "请先填写服务器地址。",
  "dashboard.openwork_host_label": "OpenWork 服务器地址",
  "dashboard.openwork_host_placeholder": "https://your-server.openwork.app",
  "dashboard.openwork_host_hint": "使用 OpenWork 服务器提供的地址。",
  "dashboard.openwork_host_token_label": "访问令牌",
  "dashboard.openwork_host_token_placeholder": "粘贴你的令牌",
  "dashboard.openwork_host_token_hint": "可选。粘贴服务器提供的访问令牌以验证。",
  "dashboard.remote_mode_openwork_alpha": "OpenWork 服务器",
  "dashboard.remote_mode_direct": "直连（旧版）",
  "dashboard.remote_connection_openwork": "OpenWork",
  "dashboard.remote_connection_direct": "直连",
  "dashboard.remote_directory_label": "工作区目录（可选）",
  "dashboard.remote_directory_placeholder": "/home/team/project",
  "dashboard.remote_directory_hint": "留空则使用服务器默认目录。",
  "dashboard.remote_display_name_label": "显示名称（可选）",
  "dashboard.remote_display_name_placeholder": "设计团队工作区",
  "dashboard.select_folder": "选择文件夹",
  "dashboard.choose_folder": "选择文件夹",
  "dashboard.choose_folder_next": "与您的工作区共享文件。",
  "dashboard.change": "更改",
  "dashboard.opening": "正在打开...",
  "dashboard.choose_preset": "选择预设",
  "dashboard.choose_folder_continue": "选择文件夹以继续。",
  "dashboard.starter_workspace": "启动工作区",
  "dashboard.starter_workspace_desc": "预配置以展示如何使用插件、命令和技能。",
  "dashboard.empty_workspace": "空白工作区",
  "dashboard.empty_workspace_desc": "从空白文件夹开始，添加您需要的内容。",

  // ==================== Workspace ====================
  "workspace.rename_title": "编辑工作区名称",
  "workspace.rename_description": "更新侧边栏中显示的名称。",
  "workspace.rename_label": "工作区名称",
  "workspace.rename_placeholder": "设计团队工作区",

  // ==================== Session ====================
  "session.no_selected": "未选择会话",
  "session.back_to_dashboard": "返回仪表盘",
  "session.new_task": "新建任务",
  "session.recents": "最近",
  "session.recents_notice": "这些任务在本地运行，不会跨设备同步。",
  "session.ready_to_work_title": "准备就绪",
  "session.ready_to_work_description": "描述一个任务。我会显示进度并在需要时请求权限。",
  "session.document_label": "文档",
  "session.standard_label": "标准",
  "session.no_artifacts_fallback": "还没有工件。",
  "session.active_plugins_label": "活动插件",
  "session.active_plugins_count": "{count}",
  "session.no_plugins_loaded": "未加载插件。",
  "session.selected_folders_label": "选中的文件夹",
  "session.selected_folders_count": "{count}",
  "session.working_files_label": "工作文件",
  "session.none_yet_label": "还没有。",
  "session.permission_required_title": "需要权限",
  "session.permission_required_description": "OpenCode 正在请求权限以继续。",
  "session.permission_label_uppercase": "权限",
  "session.scope_label_uppercase": "范围",
  "session.details_label": "详情",
  "session.steps_notice_text": "步骤将随着任务的展开而显示。",
  "session.ready_to_work": "准备就绪",
  "session.ready_description": "描述一个任务。我会显示进度并在需要时请求权限。",
  "session.hide_steps": "隐藏步骤",
  "session.view_steps": "查看步骤",
  "session.open": "打开",
  "session.reveal": "在文件管理器中显示",
  "session.opened_toast": "已在默认应用中打开。",
  "session.revealed_toast": "已在文件管理器中显示。",
  "session.artifact_path_missing": "工件路径缺失。",
  "session.desktop_only": "打开功能仅在桌面应用中可用。",
  "session.open_failed": "无法打开工件。",
  "session.model": "模型",
  "session.ready": "就绪",
  "session.connect_provider": "连接提供商以进行自定义。",
  "session.running": "运行中",
  "session.progress": "进度",
  "session.steps_notice": "步骤将随着任务的展开而显示。",
  "session.artifacts": "工件",
  "session.no_artifacts": "还没有工件。",
  "session.context": "上下文",
  "session.active_plugins": "活动插件",
  "session.no_plugins": "未加载插件。",
  "session.selected_folders": "选中的文件夹",
  "session.working_files": "工作文件",
  "session.none_yet": "还没有。",
  "session.document": "文档",
  "session.standard": "标准",
  "session.try_notion_prompt": "立即尝试：在 Notion 中设置我的 CRM",
  "session.insert_prompt": "插入提示",
  "session.placeholder": "向 OpenWork 提问...",
  "session.run": "运行",
  "session.permission_required": "需要权限",
  "session.permission_description": "OpenCode 正在请求权限以继续。",
  "session.permission_label": "权限",
  "session.scope_label": "范围",
  "session.details": "详情",
  "session.deny": "拒绝",
  "session.once": "一次",
  "session.allow_for_session": "在会话期间允许",

  "session.tasks_local_hint": "这些任务在本地运行，不会跨设备同步。",
  "session.recents_label": "最近",
  "session.model_standard": "标准",
  "session.run_button_title": "运行",
  "session.rename_title": "重命名会话",
  "session.rename_description": "更新此会话名称。",
  "session.rename_label": "会话名称",
  "session.rename_placeholder": "输入新的名称",

  // ==================== Commands ====================
  "commands.new": "新建",
  "commands.empty_state": "保存提示词或命令，一键重复运行。",
  "commands.workspace": "此工作区",
  "commands.global": "所有工作区",
  "commands.other": "其他命令",
  "commands.run": "运行",
  "commands.modal_title": "保存可复用流程",
  "commands.modal_description": "保存提示词或命令，便于快速复用。",
  "commands.name_label": "命令名称",
  "commands.name_placeholder": "例如：daily-standup",
  "commands.name_hint": "将在 OpenCode 中显示为 /daily-standup。",
  "commands.description_label": "描述（可选）",
  "commands.description_placeholder": "这个命令做什么？",
  "commands.template_label": "指令",
  "commands.template_placeholder": "编写你想复用的指令…",
  "commands.template_hint": "使用 $ARGUMENTS 来接收详情参数。",
  "commands.details_required": "详情",
  "commands.default_description": "运行保存的命令",
  "commands.command_label": "命令",
  "commands.details_label": "详情",
  "commands.details_placeholder": "添加可选详情",
  "commands.details_hint": "这些详情将传给命令。",
  "commands.run_modal_title": "运行命令",
  "commands.run_modal_description": "运行前可添加详情。",
  "commands.run_modal_run": "运行命令",
  "commands.name_will_be": "将创建为",
  "commands.override_title": "替换现有命令？",
  "commands.override_description": "已存在同名命令。",
  "commands.override_warning": "这将替换现有的 \"{name}\" 命令。此操作无法撤销。",
  "commands.override_confirm": "替换",
  "commands.override_cancel": "保留现有",

  // ==================== Skills ====================
  "skills.title": "Skills",
  "skills.subtitle": "管理此工作区的 skills。",
  "skills.refresh": "刷新",
  "skills.add_title": "添加 skills",
  "skills.add_description": "安装起始命令、导入 skill，或打开文件夹。",
  "skills.install_from_openpackage": "从 OpenPackage 安装",
  "skills.host_mode_only": "仅本地工作区",
  "skills.install": "安装",
  "skills.installed_label": "已安装",
  "skills.install_hint": "将 OpenPackage 包安装到当前工作区。Skills 应放在 `.opencode/skills` 中。",
  "skills.import_local": "导入本地 skill",
  "skills.import_local_hint": "将现有 skill 文件夹复制到此工作区。",
  "skills.import": "导入",
  "skills.curated_packages": "精选包",
  "skills.view": "查看",
  "skills.search_placeholder": "搜索包或列表（例如：claude、registry、community）",
  "skills.no_matches": "没有匹配的精选包。尝试不同的搜索。",
  "skills.install_package": "安装",
  "skills.registry_notice": "发布到 OpenPackage 注册表（`opkg push`）目前需要身份验证。计划添加注册表搜索和精选列表同步。",
  "skills.installed": "已安装的 skills",
  "skills.no_skills": "在 `.opencode/skills` 或 `.claude/skills` 中未检测到 skills。",
  "skills.desktop_required": "技能管理需要桌面应用。",
  "skills.host_only_error": "技能管理需要本地工作区或已连接的 OpenWork 服务器。",
  "skills.install_skill_creator": "安装 skill creator",
  "skills.install_skill_creator_hint": "此 skill 可让你在聊天中创建其他 skills。",
  "skills.installing_skill_creator": "正在安装 skill creator...",
  "skills.skill_creator_installed": "Skill creator 已安装。",
  "skills.skill_creator_already_installed": "Skill creator 已经安装过了。",
  "skills.install_failed": "技能安装失败。",
  "skills.reveal_folder": "打开 skills 文件夹",
  "skills.reveal_folder_hint": "在 Finder 中打开 skills 目录。",
  "skills.reveal_button": "在 Finder 中显示",
  "skills.reveal_failed": "打开 skills 文件夹失败。",
  "skills.uninstall": "卸载",
  "skills.uninstall_title": "卸载 skill？",
  "skills.uninstall_warning": "这将永久从工作区删除 `{name}` skill。",
  "skills.uninstall_failed": "卸载 skill 失败。",
  "skills.uninstalled": "Skill 已删除。",
  "skills.source_placeholder": "github:anthropics/claude-code",
  "skills.notion_crm_title": "Notion CRM 增强技能",
  "skills.notion_crm_description": "为联系人、管道和跟进添加增强工作流。",
  "skills.notion_crm_card_description": "使用现成的技能丰富 Notion CRM 数据。",
  "skills.connect_host_to_load": "连接 OpenWork 服务器以加载技能。",
  "skills.pick_workspace_first": "先选择一个工作区文件夹。",
  "skills.no_skills_found": "还没有找到 skills。",
  "skills.installed_description": "此工作区可用的 skills。",
  "skills.failed_to_load": "加载 skills 失败",
  "skills.plugin_management_host_only": "插件管理需要桌面应用。",
  "skills.plugins_host_only": "插件仅在桌面应用中可用。",
  "skills.pick_project_for_plugins": "选择项目文件夹以管理项目插件。",
  "skills.pick_project_for_active": "选择项目文件夹以加载活动插件。",
  "skills.no_opencode_found": "尚未找到 opencode.json。添加插件以创建一个。",
  "skills.no_opencode_workspace": "此工作区中还没有 opencode.json。",
  "skills.failed_parse_opencode": "解析 opencode.json 失败",
  "skills.failed_load_opencode": "加载 opencode.json 失败",
  "skills.failed_load_active": "加载活动插件失败。",
  "skills.enter_plugin_name": "输入插件包名称。",
  "skills.plugin_already_listed": "插件已在 opencode.json 中列出。",
  "skills.failed_update_opencode": "更新 opencode.json 失败",
  "skills.opackage_install_host_only": "OpenPackage 安装需要桌面应用。",
  "skills.pick_project_first": "先选择一个项目文件夹。",
  "skills.enter_opackage_source": "输入 OpenPackage 源（例如：github:anthropics/claude-code）。",
  "skills.installing_opackage": "正在安装 OpenPackage...",
  "skills.install_complete": "已安装。",
  "skills.curated_list_notice": "这是一个精选列表，还不是 OpenPackage。复制链接或关注 PRD 以了解计划的注册表搜索集成。",
  "skills.import_host_only": "Skill 导入需要桌面应用。",
  "skills.select_skill_folder": "选择 skill 文件夹",
  "skills.import_failed": "导入失败（{status}）",
  "skills.imported": "已导入。",
  "skills.unknown_error": "未知错误",

  // ==================== Plugins ====================
  "plugins.title": "OpenCode 插件",
  "plugins.description": "为您的项目或全局 OpenCode 插件管理 `opencode.json`。",
  "plugins.config_label": "配置",
  "plugins.config_not_loaded": "尚未加载",
  "plugins.suggested_label": "建议的插件",
  "plugins.no_plugins_yet": "尚未配置插件。",
  "plugins.enabled_label": "已启用",
  "plugins.open_label": "打开",
  "plugins.path_label": "路径",
  "plugins.scope_project": "项目",
  "plugins.scope_global": "全局",
  "plugins.refresh": "刷新",
  "plugins.config": "配置",
  "plugins.not_loaded": "尚未加载",
  "plugins.suggested": "建议的插件",
  "plugins.hide_setup": "隐藏设置",
  "plugins.setup": "设置",
  "plugins.added": "已添加",
  "plugins.add": "添加",

  // ==================== MCPs ====================
  "mcps.title": "MCPs",
  "mcps.subtitle": "管理 OpenCode 的 MCPs（模型上下文协议）。",
  "mcps.config_label": "配置",
  "mcps.config_not_loaded": "尚未加载",
  "mcps.suggested_label": "建议的 MCPs",
  "mcps.no_mcps_yet": "尚未配置 MCPs。",
  "mcps.enabled_label": "已启用",
  "mcps.open_label": "打开",
  "mcps.path_label": "路径",
  "mcps.scope_project": "项目",
  "mcps.scope_global": "全局",
  "mcps.refresh": "刷新",
  "mcps.config": "配置",
  "mcps.not_loaded": "尚未加载",
  "mcps.suggested": "建议的 MCPs",
  "mcps.hide_setup": "隐藏设置",
  "mcps.setup": "设置",
  "mcps.added": "已添加",
  "mcps.add": "添加",
  "mcps.install_title": "安装 MCP",
  "mcps.install_description": "向您的 OpenCode 添加新 MCP。",
  "mcps.pick_project_first": "先选择一个项目文件夹。",
  "mcps.no_opencode_found": "尚未找到 opencode.json。",
  "mcps.no_opencode_workspace": "此工作区中还没有 opencode.json。",
  "mcps.failed_parse_opencode": "解析 opencode.json 失败",
  "mcps.failed_load_opencode": "加载 opencode.json 失败",
  "mcps.failed_load_active": "加载活动 MCPs 失败。",
  "mcps.pick_project_for_mcps": "选择项目文件夹以管理项目 MCPs。",
  "mcps.pick_project_for_active": "选择项目文件夹以加载活动 MCPs。",
  "mcps.enter_mcp_config": "输入 MCP 配置。",
  "mcps.mcp_already_listed": "MCP 已在 opencode.json 中列出。",
  "mcps.failed_update_opencode": "更新 opencode.json 失败",
  "mcps.invalid_json": "无效的 JSON 格式。",

  // ==================== Settings ====================
  "settings.title": "设置",
  "settings.appearance": "外观",
  "settings.language": "语言",
  "settings.theme": "主题",
  "settings.light": "浅色",
  "settings.dark": "深色",
  "settings.auto": "自动",
  "settings.account": "账户",
  "settings.logout": "退出",
  "settings.logout_title": "退出 OpenWork？",
  "settings.logout_confirm": "退出",
  "settings.logout_cancel": "取消",
  "settings.profile": "个人资料",
  "settings.model_settings": "模型设置",
  "settings.default_model": "默认模型",
  "settings.select_model": "选择模型",
  "settings.api_key": "API 密钥",
  "settings.api_key_hint": "输入您的 API 密钥。",
  "settings.save": "保存",
  "settings.saved": "已保存。",
  "settings.failed": "保存失败。",
  "settings.reset": "重置",
  "settings.reset_title": "重置所有设置？",
  "settings.reset_description": "这将清除所有保存的设置和数据。此操作无法撤销。",
  "settings.reset_confirm": "重置",
  "settings.reset_cancel": "取消",
  "settings.about": "关于",
  "settings.version": "版本",
  "settings.built": "构建于",
  "settings.source": "源代码",
  "settings.open": "打开",
  "settings.copy": "复制",
  "settings.copied": "已复制。",
  "settings.check_updates": "检查更新",
  "settings.checking": "正在检查...",
  "settings.up_to_date": "已是最新版本。",
  "settings.update_available": "有新版本可用。",
  "settings.download": "下载",
  "settings.open_download_page": "打开下载页面",
  "settings.update_failed": "检查更新失败。",

  // ==================== Error Messages ====================
  "error.title": "发生错误",
  "error.description": "出了点问题。请稍后重试。",
  "error.retry": "重试",
  "error.back": "返回",
  "error.not_found": "找不到。",
  "error.access_denied": "访问被拒绝。",
  "error.network_error": "网络错误。",
  "error.timeout": "操作超时。",
  "error.invalid_input": "无效的输入。",
  "error.required_field": "此字段为必填项。",
  "error.invalid_format": "格式无效。",
  "error.duplicate": "已存在。",
  "error.not_empty": "不能为空。",
  "error.min_length": "最少 {min} 个字符。",
  "error.max_length": "最多 {max} 个字符。",
  "error.permissions": "权限不足。",
  "error.workspace_not_found": "找不到工作区。",
  "error.session_not_found": "找不到会话。",
  "error.task_not_found": "找不到任务。",
  "error.invalid_workspace": "无效的工作区。",
  "error.invalid_session": "无效的会话。",
  "error.invalid_task": "无效的任务。",

  // ==================== Common ====================
  "common.save": "保存",
  "common.cancel": "取消",
  "common.delete": "删除",
  "common.edit": "编辑",
  "common.close": "关闭",
  "common.back": "返回",
  "common.next": "下一步",
  "common.previous": "上一步",
  "common.confirm": "确认",
  "common.loading": "加载中...",
  "common.empty": "空",
  "common.no_data": "暂无数据",
  "common.search": "搜索",
  "common.clear": "清空",
  "common.copy": "复制",
  "common.copied": "已复制",
  "common.open": "打开",
  "common.share": "分享",
  "common.download": "下载",
  "common.upload": "上传",
  "common.create": "创建",
  "common.update": "更新",
  "common.delete": "删除",
  "common.remove": "移除",
  "common.add": "添加",
  "common.more": "更多",
  "common.less": "收起",
  "common.all": "全部",
  "common.none": "无",
  "common.yes": "是",
  "common.no": "否",
  "common.ok": "确定",
  "common.gotit": "明白",
  "common.today": "今天",
  "common.yesterday": "昨天",
  "common.week": "这一周",
  "common.month": "这一个月",
  "common.year": "今年",
  "common.unknown": "未知",
  "common.error": "错误",
  "common.success": "成功",
  "common.warning": "警告",
  "common.info": "信息",
  "common.required": "必填",
  "common.optional": "可选",
  "common.default": "默认",
  "common.custom": "自定义",
  "common.active": "活跃",
  "common.inactive": "不活跃",
  "common.enabled": "已启用",
  "common.disabled": "已禁用",
  "common.visible": "可见",
  "common.hidden": "隐藏",
  "common.public": "公开",
  "common.private": "私有",
  "common.draft": "草稿",
  "common.published": "已发布",
  "common.archived": "已存档",
  "common.pinned": "已固定",
  "common.recent": "最近",
  "common.popular": "热门",
  "common.new": "新",
  "common.updated": "更新时间",
  "common.created": "创建时间",
  "common.deleted": "已删除",
  "common.expires": "过期时间",
  "common.never": "从不",
  "common.always": "始终",
  "common.sometimes": "有时",
  "common.unavailable": "不可用",
  "common.available": "可用",
  "common.working": "处理中",
  "common.done": "完成",
  "common.processing": "处理中",
  "common.queued": "排队中",
  "common.canceled": "已取消",
  "common.failed": "失败",
  "common.success": "成功",
  "common.retrying": "重试中",
  "common.offline": "离线",
  "common.online": "在线",
  "common.sync": "同步",
  "common.syncing": "同步中",
  "common.synced": "已同步",
  "common.unsaved": "未保存",
};
