#!/usr/bin/env bash
# =============================================================================
# sync-upstream.sh — 拉取 upstream dev，rebase 本地 dev，运行 i18n 补丁
#
# 用法:
#   ./scripts/sync-upstream.sh             # 完整流程（fetch + rebase + i18n）
#   ./scripts/sync-upstream.sh --fetch-only  # 只 fetch，不 rebase
#   ./scripts/sync-upstream.sh --i18n-only   # 只跑 i18n 补丁，不 fetch/rebase
#
# 前置要求:
#   git, python3 (用于 patch-i18n.py)
#   upstream remote 指向 https://github.com/different-ai/openwork
# =============================================================================

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SCRIPT_DIR="$REPO_ROOT/scripts"
I18N_SCRIPT="$SCRIPT_DIR/patch-i18n.py"
UPSTREAM_REMOTE="upstream"
UPSTREAM_BRANCH="dev"
LOCAL_BRANCH="dev"
PUSH_REMOTE="nurdich"

# ── 颜色输出 ──────────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; BLUE='\033[0;34m'; NC='\033[0m'
info()  { echo -e "${BLUE}[sync]${NC} $*"; }
ok()    { echo -e "${GREEN}[ok]${NC}   $*"; }
warn()  { echo -e "${YELLOW}[warn]${NC} $*"; }
die()   { echo -e "${RED}[error]${NC} $*" >&2; exit 1; }

# ── 参数解析 ──────────────────────────────────────────────────────────────────
FETCH_ONLY=false
I18N_ONLY=false
for arg in "$@"; do
  case "$arg" in
    --fetch-only) FETCH_ONLY=true ;;
    --i18n-only)  I18N_ONLY=true  ;;
    --help|-h)
      sed -n '2,16p' "$0" | sed 's/^# //; s/^#//'
      exit 0
      ;;
    *) die "未知参数: $arg" ;;
  esac
done

cd "$REPO_ROOT"

# ── 安全检查 ──────────────────────────────────────────────────────────────────
check_clean_working_tree() {
  # Windows autocrlf 导致 git diff 假阳性。用 git status --porcelain
  # 只检查真实状态变化（M 、A 、D），忽略 CRLF 警告。
  git update-index -q --refresh 2>/dev/null || true
  local status_out
  status_out="$(git status --porcelain 2>/dev/null | grep -E '^[MADRCU]' || true)"
  if [[ -n "$status_out" ]]; then
    warn "工作区有未提交的变更："
    echo "$status_out" | head -20 | sed 's/^/  /'
    die "请先 commit 或 stash 后重试"
  fi
}

check_on_branch() {
  local current
  current="$(git rev-parse --abbrev-ref HEAD)"
  if [[ "$current" != "$LOCAL_BRANCH" ]]; then
    die "当前分支为 '$current'，请先切换到 '$LOCAL_BRANCH'"
  fi
}

# ── i18n 补丁 ─────────────────────────────────────────────────────────────────
run_i18n_patch() {
  if [[ ! -f "$I18N_SCRIPT" ]]; then
    warn "未找到 $I18N_SCRIPT，跳过 i18n 补丁"
    return
  fi

  info "运行 i18n 补丁脚本..."
  python3 "$I18N_SCRIPT" "$REPO_ROOT"

  # 如果 zh.ts 有变更则自动提交
  if ! git diff --quiet -- packages/app/src/i18n/locales/zh.ts; then
    local upstream_ver
    upstream_ver="$(git log -1 --format="%h" "${UPSTREAM_REMOTE}/${UPSTREAM_BRANCH}" 2>/dev/null || echo "unknown")"
    git add packages/app/src/i18n/locales/zh.ts
    git commit -m "fix(i18n): sync zh.ts to upstream ${upstream_ver}

Auto-generated by scripts/sync-upstream.sh
New keys translated to Chinese; untranslated keys marked with [TODO]"
    ok "zh.ts 补丁已提交"
  else
    ok "zh.ts 无需更新"
  fi
}

# ── 主流程 ────────────────────────────────────────────────────────────────────
if $I18N_ONLY; then
  info "模式: 仅 i18n 补丁"
  run_i18n_patch
  exit 0
fi

check_clean_working_tree
check_on_branch

# 1. Fetch upstream
info "拉取 ${UPSTREAM_REMOTE}/${UPSTREAM_BRANCH}..."
git fetch "$UPSTREAM_REMOTE" "$UPSTREAM_BRANCH"

UPSTREAM_REF="${UPSTREAM_REMOTE}/${UPSTREAM_BRANCH}"
LOCAL_HASH="$(git rev-parse HEAD)"
UPSTREAM_HASH="$(git rev-parse "$UPSTREAM_REF")"

if [[ "$LOCAL_HASH" == "$UPSTREAM_HASH" ]]; then
  ok "本地已是最新，无需 rebase"
  run_i18n_patch
  exit 0
fi

AHEAD="$(git rev-list "${UPSTREAM_REF}..HEAD" --count)"
BEHIND="$(git rev-list "HEAD..${UPSTREAM_REF}" --count)"
info "本地领先 upstream ${AHEAD} 个提交，upstream 领先本地 ${BEHIND} 个提交"

if $FETCH_ONLY; then
  info "模式: 仅 fetch，不 rebase"
  info "运行以下命令继续:"
  echo "  git rebase ${UPSTREAM_REF}"
  exit 0
fi

# 2. Rebase
info "开始 rebase: git rebase ${UPSTREAM_REF}..."

REBASE_LOG="$(mktemp)"
set +e
git rebase "$UPSTREAM_REF" > "$REBASE_LOG" 2>&1
REBASE_EXIT=$?
set -e

if [[ $REBASE_EXIT -ne 0 ]]; then
  echo ""
  warn "========================================="
  warn "  Rebase 遇到冲突，需要手动解决"
  warn "========================================="
  echo ""
  echo "冲突文件："
  git diff --name-only --diff-filter=U | sed '  s/^/  /'
  echo ""
  echo "解决步骤:"
  echo "  1. 编辑冲突文件，搜索 <<<<< 标记"
  echo "  2. git add <已解决的文件>"
  echo "  3. git rebase --continue"
  echo "  4. 重复直到 rebase 完成"
  echo "  5. 重新运行本脚本补全 i18n 补丁:"
  echo "     ./scripts/sync-upstream.sh --i18n-only"
  echo ""
  echo "放弃 rebase:"
  echo "  git rebase --abort"
  rm -f "$REBASE_LOG"
  exit 1
fi
rm -f "$REBASE_LOG"
ok "Rebase 完成"

# 3. i18n 补丁
run_i18n_patch

# 4. 推送
info "推送到 ${PUSH_REMOTE}/dev..."
git push "$PUSH_REMOTE" "$LOCAL_BRANCH" --force-with-lease
ok "推送完成: https://github.com/Nurdich/openwork/tree/${LOCAL_BRANCH}"

echo ""
ok "========================================"
ok "  同步完成！"
ok "  upstream: $(git rev-parse --short ${UPSTREAM_REF})"
ok "  local:    $(git rev-parse --short HEAD)"
ok "========================================"
