#!/usr/bin/env python3
# -*- coding: utf-8 -*-
from __future__ import annotations
import argparse
import io
import subprocess
import sys
from pathlib import Path

# Windows GBK 控制台强制 UTF-8 输出，避免中文乱码
_enc = getattr(sys.stdout, 'encoding', '') or ''
if _enc.lower().replace('-', '') not in ('utf8', 'utf-8'):
    try:
        sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8', errors='replace')
        sys.stderr = io.TextIOWrapper(sys.stderr.buffer, encoding='utf-8', errors='replace')
    except Exception:
        pass

# ── 配置 ───────────────────────────────────────────────────────────────────────
UPSTREAM_REMOTE = "upstream"
UPSTREAM_BRANCH = "dev"
LOCAL_BRANCH    = "dev"
PUSH_REMOTE     = "nurdich"

REPO_ROOT   = Path(__file__).resolve().parent.parent
I18N_SCRIPT = REPO_ROOT / "scripts" / "patch-i18n.py"

# ── 颜色（Windows 10+ 支持 ANSI，旧版自动降级） ────────────────────────────────
try:
    import ctypes
    ctypes.windll.kernel32.SetConsoleMode(
        ctypes.windll.kernel32.GetStdHandle(-11), 7
    )
    _COLOR = True
except Exception:
    _COLOR = False

def _c(code: str, text: str) -> str:
    return f"\033[{code}m{text}\033[0m" if _COLOR else text

def info(msg: str)  -> None: print(_c("34", f"[sync] {msg}"))
def ok(msg: str)    -> None: print(_c("32", f"[ok]   {msg}"))
def warn(msg: str)  -> None: print(_c("33", f"[warn] {msg}"), file=sys.stderr)
def die(msg: str)   -> None:
    print(_c("31", f"[error] {msg}"), file=sys.stderr)
    sys.exit(1)

# ── git 工具 ───────────────────────────────────────────────────────────────────
def git(*args: str, capture: bool = False, check: bool = True) -> subprocess.CompletedProcess:
    cmd = ["git", *args]
    return subprocess.run(
        cmd, cwd=REPO_ROOT,
        capture_output=capture,
        text=True,
        check=check,
    )

def git_out(*args: str) -> str:
    return git(*args, capture=True).stdout.strip()

def git_rc(*args: str) -> int:
    return subprocess.run(
        ["git", *args], cwd=REPO_ROOT,
        capture_output=True, text=True
    ).returncode

# ── 安全检查 ───────────────────────────────────────────────────────────────────
def check_clean_working_tree() -> None:
    git("update-index", "-q", "--refresh", check=False)
    result = subprocess.run(
        ["git", "status", "--porcelain"],
        cwd=REPO_ROOT, capture_output=True, text=True
    )
    dirty = [l for l in result.stdout.splitlines() if l[:2].strip() in ("M","A","D","R","C","U")]
    if dirty:
        warn("工作区有未提交的变更：")
        for line in dirty[:20]:
            print(f"  {line}")
        die("请先 commit 或 stash 后重试")

def check_on_branch() -> None:
    current = git_out("rev-parse", "--abbrev-ref", "HEAD")
    if current != LOCAL_BRANCH:
        die(f"当前分支为 '{current}'，请先切换到 '{LOCAL_BRANCH}'")

# ── i18n 补丁 ─────────────────────────────────────────────────────────────────
def run_i18n_patch() -> None:
    if not I18N_SCRIPT.exists():
        warn(f"未找到 {I18N_SCRIPT}，跳过 i18n 补丁")
        return

    info("运行 i18n 补丁脚本...")
    result = subprocess.run(
        [sys.executable, str(I18N_SCRIPT), str(REPO_ROOT)],
        cwd=REPO_ROOT
    )

    if result.returncode == 1:
        die("i18n 补丁脚本执行失败")

    if result.returncode == 2:
        # 有新 key 写入，提交
        try:
            upstream_ver = git_out(
                "log", "-1", "--format=%h",
                f"{UPSTREAM_REMOTE}/{UPSTREAM_BRANCH}"
            )
        except Exception:
            upstream_ver = "unknown"

        git("add", "packages/app/src/i18n/locales/zh.ts")
        git("commit", "-m",
            f"fix(i18n): sync zh.ts to upstream {upstream_ver}\n\n"
            "Auto-generated by scripts/sync_upstream.py\n"
            "New keys translated to Chinese; untranslated keys marked with [TODO]"
        )
        ok("zh.ts 补丁已提交")
    else:
        ok("zh.ts 无需更新")

# ── 主流程 ────────────────────────────────────────────────────────────────────
def main() -> None:
    parser = argparse.ArgumentParser(
        description="拉取 upstream dev，rebase 本地分支，同步 i18n 补丁",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument("--fetch-only", action="store_true", help="只 fetch，不 rebase")
    parser.add_argument("--i18n-only",  action="store_true", help="只跑 i18n 补丁")
    args = parser.parse_args()

    if args.i18n_only:
        info("模式: 仅 i18n 补丁")
        run_i18n_patch()
        return

    check_clean_working_tree()
    check_on_branch()

    # 1. Fetch
    info(f"拉取 {UPSTREAM_REMOTE}/{UPSTREAM_BRANCH}...")
    git("fetch", UPSTREAM_REMOTE, UPSTREAM_BRANCH)

    upstream_ref = f"{UPSTREAM_REMOTE}/{UPSTREAM_BRANCH}"
    local_hash    = git_out("rev-parse", "HEAD")
    upstream_hash = git_out("rev-parse", upstream_ref)

    if local_hash == upstream_hash:
        ok("本地已是最新，无需 rebase")
        run_i18n_patch()
        return

    ahead  = git_out("rev-list", f"{upstream_ref}..HEAD", "--count")
    behind = git_out("rev-list", f"HEAD..{upstream_ref}", "--count")
    info(f"本地领先 upstream {ahead} 个提交，upstream 领先本地 {behind} 个提交")

    if args.fetch_only:
        info("模式: 仅 fetch，不 rebase")
        info("运行以下命令继续:")
        print(f"  git rebase {upstream_ref}")
        return

    # 2. Rebase
    info(f"开始 rebase: git rebase {upstream_ref}...")
    rebase = subprocess.run(
        ["git", "rebase", upstream_ref],
        cwd=REPO_ROOT, text=True, capture_output=True
    )

    if rebase.returncode != 0:
        print()
        warn("=========================================")
        warn("  Rebase 遇到冲突，需要手动解决")
        warn("=========================================")
        print()
        conflict_result = subprocess.run(
            ["git", "diff", "--name-only", "--diff-filter=U"],
            cwd=REPO_ROOT, capture_output=True, text=True
        )
        print("冲突文件：")
        for f in conflict_result.stdout.strip().splitlines():
            print(f"  {f}")
        print()
        print("解决步骤:")
        print("  1. 用编辑器打开冲突文件，搜索 <<<< 标记")
        print("  2. git add <已解决的文件>")
        print("  3. git rebase --continue")
        print("  4. 重复直到 rebase 完成")
        print("  5. 重新运行本脚本补全 i18n 补丁:")
        print("       python scripts/sync_upstream.py --i18n-only")
        print()
        print("放弃 rebase:")
        print("  git rebase --abort")
        sys.exit(1)

    ok("Rebase 完成")

    # 3. i18n 补丁
    run_i18n_patch()

    # 4. 推送
    info(f"推送到 {PUSH_REMOTE}/dev...")
    git("push", PUSH_REMOTE, LOCAL_BRANCH, "--force-with-lease")
    ok(f"推送完成: https://github.com/Nurdich/openwork/tree/{LOCAL_BRANCH}")

    print()
    ok("========================================")
    ok("  同步完成！")
    ok(f"  upstream: {git_out('rev-parse', '--short', upstream_ref)}")
    ok(f"  local:    {git_out('rev-parse', '--short', 'HEAD')}")
    ok("========================================")


if __name__ == "__main__":
    main()
